version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.0.0-alpine
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    networks:
      - traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(``)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt

networks:
  traefik_net:
    external:
      name: traefik_net
