name: Dionysus

on:
  push:
    paths:
      - "hosts/dionysus/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - run: nixos-rebuild build
